apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hostpath-exec-cronjob
  labels:
    app: pentest
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hostpath-exec-cronjob
            image: ubuntu
            volumeMounts:
            - mountPath: /host
              name: noderoot
            command: [ "/bin/sh", "-c", "--" ]
            args: [ "while true; do sleep 30; done;" ]
          #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
          volumes:
          - name: noderoot
            hostPath:
              path: /
          restartPolicy: OnFailure
